server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: ecom-service
          uri: lb://ecom-service
          predicates:
            - Path=/product/**, /customer/**, /buy-cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: ecomCircuit
                fallbackUri: forward:/fallback/ecom
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

        - id: discount-calculator-service
          uri: lb://discount-service
          predicates:
            - Path=/api/discount/**
          filters:
            - name: CircuitBreaker
              args:
                name: discountCircuit
                fallbackUri: forward:/fallback/discount
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

      default-filters:
        - AddResponseHeader=X-Gateway, API Gateway

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
  service-url:
    defaultZone: http://localhost:8761/eureka/
