server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
  service-url:
    defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.example.DiscountCalculator: INFO

my:
  test:
    property: "💸 Discount service config is working!"
