server:
  port: 8082

spring:
  application:
    name: ecom-service

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Ecomdb

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
